# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - build
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build_dev:
    stage: build
    script:
        - npm install
        - npm run build
        
deploy_prod:
    stage: deploy
    script:
        - apt-get update -yq
        - apt-get install -y ruby ruby-dev rubygems-integration
        - gem install dpl
        - dpl --provider=heroku --app=group-3-tempeturs-frontend --api-key=$MORGAN_HEROKU_API_KEY --skip_cleanup
    only:
    - master
